# Presentation and Paper {#final}

## Presentation

### Presentation Procedure: 

1. Everyone accesses to the course Zoom account

2. Prepare presentation slides on your own PC.

3. Each person gives a presentation according to the list. (Each person has 7 minutes).

4. Presenters project their presentation slides onto the Zoom screen using the screen sharing function. 

5. Presenter unmutes and delivers the presentation. 

6. The next presenter prepares his/her slides and waits.

### Submission: Notebook file and the Presentation file

Please submit the following.

Notebook files and presentation slides used in the presentation (if the presentation is given in R Notebook, no slides are required).

Deadline: 23:59 of February 25. 

## Final Report

### Submission of a Final Report

Students are required to submit a final report on a research topic.

1. Students select a research topic.
2. Collecting data on your research topic.
3. Analyze data using methods learnt in lectures.
4. Discuss about your findings.

The format of the report is not specified, but the following is an example.

Content of a final report:

1. Title of your research
2. Abstract
3. Data
4. Analysing data
5. Findings
6. Discussion
7. References.

Students are requested to submit a paper, with a supporting document in R Notebook to prepare your essay. Submit the PDF file of the final report and the R Notebbok file on Moodle.

Length: less than 8 pages in A4 format including figures and tables.　Upload it on Moodle. 

Deadline of submission: March 08. 

## Topics Chosen by Students

1. Migration and Economic performance

2. Education Costs and Fertility Rate in Japan

3. Analysis of Athletes Nations Distribution and Gender Equality in the Olympics

4. The correlation between the trade surplus and the economic development

5.

6.

7.

8.

9.

10.

11.

12.

13.

14.

15.

16.

17.

18.

